### PR TITLE
CM v2.3.5 release

### PR DESCRIPTION
**Pull request by gfursin**

### CODE REVIEW

**Comment by gfursin** [comment]
Hi @arjunsuresh and @anandhu-eng . 

I added a prototype of "cm init" where I moved part of your setup.py code from mlcommons@cm4mlops to the standard CM function (https://github.com/mlcommons/ck/blob/dev/cm/cmind/repo/automation/core/module.py#L16).

Therefore instead of `pip install cm4mlops` we can use a proper way with an interactive control, flags and proper error handling: 
`pip install cmind && cm init`

For example, we can use
```
pip install cmind && cm init --quiet --repo=mlcommons@cm4mlops --branch=mlperf-inference
```

**Comment by gfursin** [comment]
This function will be available in the CM v2.3.5 release.

**Review by ctuning-admin — APPROVED** [review]
Approved.

**Comment by arjunsuresh** [comment]
> Hi @arjunsuresh and @anandhu-eng .
> 
> I added a prototype of "cm init" where I moved part of your setup.py code from mlcommons@cm4mlops to the standard CM function (https://github.com/mlcommons/ck/blob/dev/cm/cmind/repo/automation/core/module.py#L16).
> 
> Therefore instead of `pip install cm4mlops` we can use a proper way with an interactive control, flags and proper error handling: `pip install cmind && cm init`
> 
> For example, we can use
> 
> ```
> pip install cmind && cm init --quiet --repo=mlcommons@cm4mlops --branch=mlperf-inference
> ```

That's nice Grigori.

**Pull request merged**
