### PR TITLE
Merge from cTuning

### PR DESCRIPTION
**Pull request by arjunsuresh**

### CODE REVIEW

**Review by gfursin — APPROVED** [review]
LGTM

**Comment by gfursin** [comment]
@arjunsuresh - hmm, still fails on a couple of tests

**Comment by arjunsuresh** [comment]
@gfursin  tf python reference implementation is segfaulting -- we don't have any change affecting this. This was not reproducible on macOS. Will try it on a linux machine.

**Comment by gfursin** [comment]
Oh, sorry, missed your message ...

**Comment by gfursin** [comment]
Hmm, that's weird. But there is another non-TF fail?

**Comment by gfursin** [comment]
Maybe some glitches with GitHub?

**Comment by arjunsuresh** [comment]
No Grigori. The issue is reproducible on linux. It is the TF reference implementation segfaulting and this is actually happening even for the CK master branch - so the issue is not related to this PR. Both TF 2.13 and 2.12 are giving segfaults. gdb showed this

```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x0000ffff8ab095c8 in upb_Message_DeepCopy () from /home/cmuser/.local/lib/python3.10/site-packages/google/_upb/_message.abi3.so
(gdb) bt
#0  0x0000ffff8ab095c8 in upb_Message_DeepCopy () from /home/cmuser/.local/lib/python3.10/site-packages/google/_upb/_message.abi3.so
#1  0x0000ffff8ab04e04 in PyUpb_Message_CopyFrom () from /home/cmuser/.local/lib/python3.10/site-packages/google/_upb/_message.abi3.so
#2  0x0000aaaac9b133c4 in ?? ()
#3  0x0000aaaac9b02ce8 in _PyEval_EvalFrameDefault ()
#4  0x0000aaaac9b14808 in _PyFunction_Vectorcall ()
#5  0x0000aaaac9b003b0 in _PyEval_EvalFrameDefault ()
#6  0x0000aaaac9b14808 in _PyFunction_Vectorcall ()
#7  0x0000aaaac9b02ce8 in _PyEval_EvalFrameDefault ()
#8  0x0000aaaac9b14808 in _PyFunction_Vectorcall ()
#9  0x0000aaaac9b02ce8 in _PyEval_EvalFrameDefault ()
#10 0x0000aaaac9b14808 in _PyFunction_Vectorcall ()
#11 0x0000aaaac9afeb94 in _PyEval_EvalFrameDefault ()
#12 0x0000aaaac9b2347c in ?? ()
#13 0x0000aaaac9affb9c in _PyEval_EvalFrameDefault ()
#14 0x0000aaaac9b14808 in _PyFunction_Vectorcall ()
#15 0x0000aaaac9afeb94 in _PyEval_EvalFrameDefault ()
#16 0x0000aaaac9bf7604 in ?? ()
#17 0x0000aaaac9bf7514 in PyEval_EvalCode ()
#18 0x0000aaaac9c2d6ec in ?? ()
#19 0x0000aaaac9c24d94 in ?? ()
#20 0x0000aaaac9c2d37c in ?? ()
#21 0x0000aaaac9c2c464 in _PyRun_SimpleFileObject ()
#22 0x0000aaaac9c2c104 in _PyRun_AnyFileObject ()
#23 0x0000aaaac9c1ab5c in Py_RunMain ()
#24 0x0000aaaac9be8b48 in Py_BytesMain ()
#25 0x0000ffff97667780 in __libc_start_call_main (main=main@entry=0xaaaac9be8b20, argc=argc@entry=25, argv=argv@entry=0xffffd9faf308) at ../sysdeps/nptl/libc_start_call_main.h:58
#26 0x0000ffff97667858 in __libc_start_main_impl (main=0xaaaac9be8b20, argc=25, argv=0xffffd9faf308, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=<optimized out>) at ../csu/libc-start.c:381
#27 0x0000aaaac9be8a30 in _start ()
```
So apparently, the culprit is `protobuf`. Downgrading it from `4.24.0` fixed the issue.

**Comment by gfursin** [comment]
That's interesting, so it's the latest protobuf that gives this problem? Can we report it to TF GitHub and link with this bug and provide CM commands to reproduce it?

**Review by gfursin — APPROVED** [review]
LGTM

**Pull request merged**
