### PR TITLE
V2.3.7 release

### PR DESCRIPTION
**Pull request by gfursin**
- added cmind.core.debug to make it easier to debug CM automations
- added env CM_CORE_SKIP_FIX_REPO_PATH to skip fixing non-existent repo paths

### CODE REVIEW

**Comment by arjunsuresh** [comment]
Thank you @gfursin for the release. Should we automate the releases via GitHub actions?

**Comment by gfursin** [comment]
Hi @arjunsuresh.
May I ask you not to merge PRs before all the tests are passed, please?
Thanks!

**Comment by gfursin** [comment]
CM is stable and we require minor updates from time to time that can be done manually for now, but we can sync at some point how to automate this process too ... I just want to make sure that all tests are passed on MLCommons side before making a release ...

**Comment by arjunsuresh** [comment]
Sure Grigori. But there are tests like <checking of broken links` which run on code commit - hence after the PR is merged.

**Comment by gfursin** [comment]
No worries, I just prefer to wait until all tests are done to feel safe. CM is a critical component for different projects and I am  trying to double check everything ;) ...

**Pull request merged**
