### PR TITLE
Refactoring of script automation code to support variations for cm docker script

### PR DESCRIPTION
**Pull request by arjunsuresh**

### CODE REVIEW

**Review by gfursin — COMMENTED** [review]
Hi @arjunsuresh . Do you think we can move license checking outside get-cognata to the script and turn it on via meta? I think we will need to same functionality in different scripts (private ML models, Android SDK, etc) ...

**Comment by arjunsuresh** [comment]
> Hi @arjunsuresh . Do you think we can move license checking outside get-cognata to the script and turn it on via meta? I think we will need to same functionality in different scripts (private ML models, Android SDK, etc) ...

Yes Grigori. That makes sense. But currently this is a prototype - we need to agree on if it'll work. We can make a license script dependency once we finalize this.

**Comment by gfursin** [comment]
> > Hi @arjunsuresh . Do you think we can move license checking outside get-cognata to the script and turn it on via meta? I think we will need to same functionality in different scripts (private ML models, Android SDK, etc) ...
> 
> Yes Grigori. That makes sense. But currently this is a prototype - we need to agree on if it'll work. We can make a license script dependency once we finalize this.

Sure. Agree!

**Review by gfursin — APPROVED** [review]
LGTM

**Pull request merged**
