### PR TITLE
add contrib

### PR DESCRIPTION
**Pull request by nijoj**

### CODE REVIEW

**Comment by arjunsuresh** [comment]
@nijoj Can you please submit the CLA form?

**Review by arjunsuresh — APPROVED** [review]

**Comment by nijoj** [comment]
done @arjunsuresh

**Review by arjunsuresh — APPROVED** [review]

**Comment by arjunsuresh** [comment]
recheck

**Comment by arjunsuresh** [comment]
@nijoj Was there any issue with the CLA approval?

**Comment by nijoj** [comment]
@arjunsuresh no issues, just sent the CLA form to [support@mlcommons.org](mailto:support@mlcommons.org).

**Pull request merged**
