### PR TITLE
Merge from OctoML

### PR DESCRIPTION
**Pull request by arjunsuresh**

### CODE REVIEW

**Comment by gfursin** [comment]
Oh, I am very scared of the huge code just to detect a pattern. I suggest to use fnmatch that can do the same in just a few lines of code - it worked very well in CK and I use it in CM too. You can just check if '*' or '?' in the string and then apply fnmatch - that's it ... See example at https://github.com/mlcommons/ck/blob/master/cm/cmind/utils.py#L507 . We can discuss it at the conf-call ...

**Comment by gfursin** [comment]
I speak about this code: https://github.com/mlcommons/ck/pull/557/files#diff-2f7105dae03be39d8bffd4c8e3223f118168b692e7f6a125be7923970c710559R1999 ;)

**Comment by arjunsuresh** [comment]
Hi @gfursin , when we use regular expression that code is redundant and can be removed. But I didn't remove it now because it can breat our scripts until we change the file_names in customize.py to corresponding patterns to match. I'll change re.match to fnmatch as it is more portable.

**Comment by gfursin** [comment]
Ok, I see, though I think it's much more friendlier for end-users/researchers to use file patterns in our case (*?) then regular expressions. This is discussable and I accept this PR - we can check it later ...

**Review by gfursin — COMMENTED** [review]
LGTM

**Review by gfursin — APPROVED** [review]
LGTM

**Pull request merged**
