### PR TITLE
Removed old test files, fixed tests for script features and mlperf

### PR DESCRIPTION
**Pull request by arjunsuresh**

### CODE REVIEW

**Review by gfursin — COMMENTED** [review]
Interesting. 

Actually, it seems that we still need all these tests here if we do changes in CM? 

Is there a way to trigger cm4mlops tests if we do a change in this core CM repo?

Otherwise, if we remove all these tests, we will not be able to detect a problem with the main CM workflows when we update CM?

**Comment by arjunsuresh** [comment]
That's correct @gfursin . But currently these test files are not effective as they were supposed to run only when changes are made to "cm-mlops" directory. I think we should make separate test for testing CM scripts (no need for the whole MLPerf pipeline?) when CM core changes are made.

**Comment by gfursin** [comment]
> That's correct @gfursin . But currently these test files are not effective as they were supposed to run only when changes are made to "cm-mlops" directory. I think we should make separate test for testing CM scripts (no need for the whole MLPerf pipeline?) when CM core changes are made.

I think it's still useful to test just 1 MLPerf pipeline here (no need for comprehensive MLPerf tests though) besides the code CM functionality just to avoid some obvious mistakes ;) ...

**Comment by arjunsuresh** [comment]
Sure @gfursin . I have added the script features test and also the R50 test. Currently some tests are failing on Windows and macOS which needs fix in the cm4mlops repository.

**Review by gfursin — APPROVED** [review]
LGTM

**Comment by gfursin** [comment]
Actually, I just saw the problem with certificates on Windows when downloading a dataset... Is it possible to fix it, please? Thanks!

**Comment by arjunsuresh** [comment]
yes Grigori. That should be fixed in [this PR](https://github.com/mlcommons/cm4mlops/pull/237)

**Review by gfursin — APPROVED** [review]
LGTM

**Pull request merged**
